import Head from "next/head";
import estilos from "@/styles/Home.module.css";
import Topo from "@/components/Topo";
import ListaCards from "@/components/ListaCards";


export default function Home() {
  return (
    <>
      <Head>
        <title>Baralho dos Signos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <Topo />
        <ListaCards />
      </main>
    </>
  );
}
