USE DB_DEVMEDIA;

SELECT CODIGO, NOME, PRECO, PRECO + 1 AS 'PRECO_ACRESCIMO' FROM PRODUTOS;
SELECT CODIGO, NOME, PRECO FROM PRODUTOS ORDER BY PRECO DESC, NOME;
SELECT SUM(QUANTIDADE) FROM VENDAS WHERE CODIGO_PRODUTO=100;
SELECT * FROM VENDAS;
SELECT DATA_VENDA, SUM(QUANTIDADE) FROM VENDAS GROUP BY DATA_VENDA HAVING SUM(QUANTIDADE)>5;

SELECT C.CODIGO, C.NOME, V.NOME NOME_VENDEDOR
FROM CLIENTES C
RIGHT JOIN VENDEDORES V ON C.CODIGO_VENDEDOR=V.CODIGO;


SELECT COUNT(CODIGO) FROM CLIENTES GROUP BY CODIGO_VENDEDOR;

SELECT * FROM CONTAS_RECEBER;

SELECT COUNT(DISTINCT DESCRICAO) FROM CONTAS_RECEBER;



